-- Companies tablosuna eksik kolonları ekle
ALTER TABLE companies 
ADD COLUMN IF NOT EXISTS tax_number TEXT,
ADD COLUMN IF NOT EXISTS tax_office TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS sector TEXT DEFAULT 'retail',
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS invoice_prefix TEXT DEFAULT 'FTR',
ADD COLUMN IF NOT EXISTS invoice_series TEXT DEFAULT 'A',
ADD COLUMN IF NOT EXISTS last_invoice_no INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS e_invoice_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS e_invoice_username TEXT,
ADD COLUMN IF NOT EXISTS e_invoice_password TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS iban TEXT,
ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'TRY',
ADD COLUMN IF NOT EXISTS theme TEXT DEFAULT 'light',
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'tr',
ADD COLUMN IF NOT EXISTS date_format TEXT DEFAULT 'DD/MM/YYYY',
ADD COLUMN IF NOT EXISTS decimal_places INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS stock_tracking BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS negative_stock_allowed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS auto_backup BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS sms_notifications BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS whatsapp_notifications BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS low_stock_alert BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS due_payment_alert BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS alert_days_before INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW());

-- Update trigger ekle
CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
